source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GhostLoginManager_Example', :exclusive => true do
  pod "GhostLoginManager", :path => "../"
end

target 'GhostLoginManager_Tests', :exclusive => true do
  pod "GhostLoginManager", :path => "../"
end
